# NOUVELLE IMAGE DE BASE : Debian, plus robuste que Alpine
FROM php:8.3-fpm

# Mise à jour des dépôts (Étape 1)
RUN apt-get update

# Installation des dépendances système (y compris libzip-dev) (Étape 2)
RUN apt-get install -y \
    git \
    curl \
    libpq-dev \
    postgresql-client \
    unzip \
    libzip-dev \
    libmariadb-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Installation des extensions PHP (Étape 3)
RUN docker-php-ext-install pdo pdo_pgsql zip pdo_mysql

# ⚙️ Installation de Node.js + npm (Étape 4)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm

# Installation de Composer (Étape 5)
RUN curl -sS --insecure https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN sed -i 's/memory_limit = 128M/memory_limit = 256M/g' /usr/local/etc/php/php.ini
# Répertoire de travail (Étape 6)
WORKDIR /var/www
